version: "3"
services:
  database: 
    image: postgis/postgis
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 55432:5432
  database_test: 
    image: postgis/postgis
    environment: 
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_database=postgres_test
    ports:
      - 45432:5432
    
